/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface DTubeInterface extends ethers.utils.Interface {
  functions: {
    "createPost(string,string,string)": FunctionFragment;
    "name()": FunctionFragment;
    "postCount()": FunctionFragment;
    "posts(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createPost",
    values: [string, string, string]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "postCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "posts", values: [BigNumberish]): string;

  decodeFunctionResult(functionFragment: "createPost", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "postCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "posts", data: BytesLike): Result;

  events: {
    "PostCreated(uint256,string,string,string,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "PostCreated"): EventFragment;
}

export type PostCreatedEvent = TypedEvent<
  [BigNumber, string, string, string, string] & {
    id: BigNumber;
    text: string;
    hash: string;
    title: string;
    author: string;
  }
>;

export class DTube extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: DTubeInterface;

  functions: {
    createPost(
      _videoHash: string,
      _title: string,
      _text: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    name(overrides?: CallOverrides): Promise<[string]>;

    postCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    posts(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, string, string] & {
        id: BigNumber;
        text: string;
        hash: string;
        title: string;
        author: string;
      }
    >;
  };

  createPost(
    _videoHash: string,
    _title: string,
    _text: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  name(overrides?: CallOverrides): Promise<string>;

  postCount(overrides?: CallOverrides): Promise<BigNumber>;

  posts(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, string, string, string] & {
      id: BigNumber;
      text: string;
      hash: string;
      title: string;
      author: string;
    }
  >;

  callStatic: {
    createPost(
      _videoHash: string,
      _title: string,
      _text: string,
      overrides?: CallOverrides
    ): Promise<void>;

    name(overrides?: CallOverrides): Promise<string>;

    postCount(overrides?: CallOverrides): Promise<BigNumber>;

    posts(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, string, string] & {
        id: BigNumber;
        text: string;
        hash: string;
        title: string;
        author: string;
      }
    >;
  };

  filters: {
    "PostCreated(uint256,string,string,string,address)"(
      id?: null,
      text?: null,
      hash?: null,
      title?: null,
      author?: null
    ): TypedEventFilter<
      [BigNumber, string, string, string, string],
      {
        id: BigNumber;
        text: string;
        hash: string;
        title: string;
        author: string;
      }
    >;

    PostCreated(
      id?: null,
      text?: null,
      hash?: null,
      title?: null,
      author?: null
    ): TypedEventFilter<
      [BigNumber, string, string, string, string],
      {
        id: BigNumber;
        text: string;
        hash: string;
        title: string;
        author: string;
      }
    >;
  };

  estimateGas: {
    createPost(
      _videoHash: string,
      _title: string,
      _text: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    postCount(overrides?: CallOverrides): Promise<BigNumber>;

    posts(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    createPost(
      _videoHash: string,
      _title: string,
      _text: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    postCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    posts(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
